run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - gosec
    - noctx
    - nilerr

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow
  
  revive:
    rules:
      - name: var-naming
        disabled: false
      - name: exported
        disabled: false
      - name: error-return
        disabled: false
      - name: error-naming
        disabled: false
      - name: if-return
        disabled: false
      - name: var-declaration
        disabled: false
      - name: range
        disabled: false
  
  gosec:
    excludes:
      - G104
      - G304
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult
      - hugeParam

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - noctx
    
    - path: ioc/
      linters:
        - unused
  
  max-issues-per-linter: 0
  max-same-issues: 0
