version: "2"

run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gofmt
    - goimports
    - misspell
    - gocritic
    - revive
    - unconvert
    - unparam
    - gosec
    - noctx
    - nilerr

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  
  govet:
    enable-all: true
    disable:
      - shadow
  
  revive:
    rules:
      - name: var-naming
      - name: exported
      - name: error-return
      - name: error-naming
      - name: if-return
      - name: var-declaration
      - name: range
  
  gosec:
    excludes:
      - G104
      - G304
  
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - unnamedResult

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
        - noctx
    
    - path: ioc/
      linters:
        - unused
